version: "3.3"
services:
  api:
    build: api/
    image: server.alexmickelson.guru:5000/braille_api
    container_name: braille_api
    restart: always
    environment:
      - TZ=US/Central
      - JWKS_URL=${JWKS_URL}
      - AUTH_AUDIENCE=${AUTH_AUDIENCE}
      - POSTGRES_USER=braille
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=braille
  
  client:
    build: 
      context: client/
      args:
        - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
        - REACT_APP_AUTHORITY=${REACT_APP_AUTHORITY}
        - REACT_APP_HOST=${REACT_APP_HOST}
    image: server.alexmickelson.guru:5000/braille_client
    container_name: braille_client
    restart: always
    environment:
      - TZ=US/Central
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=braille
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=braille
      - TZ=America/Denver


  proxy:
    image: lscr.io/linuxserver/swag
    container_name: braille_swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
      - URL=braille.alexmickelson.guru
      # - SUBDOMAINS=www,
      - VALIDATION=http
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=<token> #optional
      - EMAIL=alexmickelson96@gmail.com
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS=<extradomains> #optional
      - STAGING=false #optional
    volumes:
      - ./nginx.conf:/config/nginx/site-confs/default.conf
      - /data/swag/:/config/
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped