export const symbols = {
  capitalSymbol: "[capital symbol]",
  capitalWord: "[capital word]",
  capitalPassageStart: "[capital passage start]",
  capitalPassageEnd: "[capital passage end]",

  italicSymbol: "[italic symbol]",
  italicWord: "[italic word]",
  italicPassageStart: "[italic passage]",
  italicPassageEnd: "[italic terminator]",

  boldSymbol: "[bold symbol]",
  boldWord: "[bold word]",
  boldPassageStart: "[bold passage]",
  boldPassageEnd: "[bold terminator]",
  
  underlineSymbol: "[underline symbol]",
  underlineWord: "[underline word]",
  underlinePassageStart: "[underline passage]",
  underlinePassageEnd: "[underline terminator]",
};

export const symbolIndicators = [
  symbols.capitalSymbol,
  symbols.italicSymbol,
  symbols.boldSymbol,
  symbols.underlineSymbol,
];
export const wordIndicators = [
  symbols.capitalWord,
  symbols.italicWord,
  symbols.boldWord,
  symbols.underlineWord,
];
export const passageStartIndicators = [
  symbols.capitalPassageStart,
  symbols.italicPassageStart,
  symbols.boldPassageStart,
  symbols.underlinePassageStart,
];

export const textLookup: { [key: string]: string } = {
  "⠀": " ",
  " ": " ",
  "⠁": "a",
  "⠃": "b",
  "⠉": "c",
  "⠙": "d",
  "⠑": "e",
  "⠋": "f",
  "⠛": "g",
  "⠓": "h",
  "⠊": "i",
  "⠚": "j",
  "⠅": "k",
  "⠇": "l",
  "⠍": "m",
  "⠝": "n",
  "⠕": "o",
  "⠏": "p",
  "⠟": "q",
  "⠗": "r",
  "⠎": "s",
  "⠞": "t",
  "⠥": "u",
  "⠧": "v",
  "⠺": "w",
  "⠭": "x",
  "⠽": "y",
  "⠵": "z",

  // "⠼": "[Numeric]",
  "⠼⠁": "1",
  "⠼⠃": "2",
  "⠼⠉": "3",
  "⠼⠙": "4",
  "⠼⠑": "5",
  "⠼⠋": "6",
  "⠼⠛": "7",
  "⠼⠓": "8",
  "⠼⠊": "9",
  "⠼⠚": "0",

  "⠠": symbols.capitalSymbol,
  "⠠⠠": symbols.capitalWord,
  "⠠⠠⠠": symbols.capitalPassageStart,
  "⠠⠄": symbols.capitalPassageEnd,

  // grade 1
  "⠰": "[symbol]",
  "⠰⠰": "[word]",
  "⠰⠰⠰": "[passage]",
  "⠰⠄ ": "[grade 1 terminator]",

  "⠨⠆": symbols.italicSymbol,
  "⠨⠂": symbols.italicWord,
  "⠨⠶": symbols.italicPassageStart,
  "⠨⠄": symbols.italicPassageEnd,

  "⠘⠆": symbols.boldSymbol,
  "⠘⠂": symbols.boldWord,
  "⠘⠶": symbols.boldPassageStart,
  "⠘⠄": symbols.boldPassageEnd,

  "⠸⠆": symbols.underlineSymbol,
  "⠸⠂": symbols.underlineWord,
  "⠸⠶": symbols.underlinePassageStart,
  "⠸⠄": symbols.underlinePassageEnd,

  "⠈⠆": "[script symbol]",
  "⠈⠂": "[script word]",
  "⠈⠶": "[script passage]",
  "⠈⠄": "[script terminator]",

  //punctuation
  "⠂": ",",
  "⠲": ".",
  "⠄": "'",
  "⠒": ":",
  "⠠⠤": "_",
  "⠐⠠⠤": "__", //long dash?
  "⠖": "!",
  "⠤": "-",
  "⠦": "?",
  "⠆": ";",
  //is an elipse just 3 periods?
  "⠸⠌": "/",
  "⠸⠡": "\\",
  // "⠦": "“" // same as question mark?
  "⠴": "”",
  "⠠⠦": "‘",
  "⠠⠴": "’",

  "⠐⠣": "(",
  "⠐⠜": ")",
  "⠨⠣": "[",
  "⠨⠜": "]",
  "⠸⠣": "{",
  "⠸⠜": "}",
  "⠈⠣": "<",
  "⠈⠜": ">",

  "⠐⠖": "+",
  "⠐⠤": "-", // is this different than a hiphen
  "⠐⠦": "·",
  "⠐⠌": "÷",
  "⠐⠶": "=",

  "⠈⠉": "¢",
  "⠈⠎": "$",
  "⠈⠑": "€",
  "⠈⠇": "£",
  "⠶": "‘", // same as ⠠⠦
  "⠶⠶": "“",

  "⠨⠴": "%",
  "⠘⠚": "°",
  "⠸⠪": "∠",
  "⠸⠹": "#",
  "⠈⠯": "&",
  "⠘⠉": "©",
  "⠘⠞": "™",
  "⠔": "[superscript indicator]",
  "⠢": "[subscript indicator]",
  "⠸⠲": "•",
  "⠈⠁": "@",
  "⠐⠔": "*",
  "⠨⠿": "[dot locator for mention]", // what?

  //strong contractions
  "⠯": "and",
  "⠿": "for",
  "⠷": "of",
  "⠮": "the",
  "⠾": "with",

  //strong wordsigns
  "⠡": "child",
  "⠩": "shall",
  "⠹": "this",
  "⠱": "which",
  "⠳": "out",
  "⠌": "still",

  //strong groupsigns
  // "⠡": "ch",
  // "⠩": "sh",
  // "⠹": "th",
  // "⠱": "wh",
  // "⠳": "ou",
  // "⠌": "st",
  "⠣": "gh",
  "⠫": "ed",
  "⠻": "er",
  "⠪": "ow",
  "⠜": "ar",
  "⠬": "ing",

  //lower groupsigns
  // '⠬': 'ea',
  // "⠆": "bb",
  // '⠒': 'cc',
  // '⠖': 'ff',
  // '⠶': 'gg',
  // '⠆': 'be',
  // '⠒': 'con',
  // '⠲': 'dis',
  // '⠢': 'en',
  // '⠔': 'in',

  //lower wordsigns
  // "⠆": "be",
  // '⠢': 'enough',
  // '⠶': 'were',
  // '⠦': 'his',
  // '⠔': 'in',
  // '⠴': 'was',

  //initial letter contractions
  "⠐⠙": "day",
  "⠐⠑": "ever",
  "⠐⠋": "father",
  "⠐⠓": "here",
  "⠐⠅": "know",
  "⠐⠇": "lord",
  "⠐⠍": "mother",
  "⠐⠝": "name",
  "⠐⠕": "one",
  "⠐⠏": "part",
  "⠐⠟": "question",
  "⠐⠗": "right",
  "⠐⠎": "some",
  "⠐⠞": "time",
  "⠐⠥": "under",
  "⠐⠺": "work",
  "⠐⠽": "young",
  "⠐⠮": "there",
  "⠐⠡": "character",
  "⠐⠹": "through",
  "⠐⠱": "where",
  "⠐⠳": "ought",
  "⠘⠥": "upon",
  "⠘⠺": "word",
  "⠘⠮": "these",
  "⠘⠹": "those",
  "⠘⠡": "whose",
  "⠸⠉": "cannot",
  "⠸⠓": "had",
  "⠸⠍": "many",
  "⠸⠎": "spirit",
  "⠸⠺": "world",
  "⠸⠮": "their",

  //final letter groupsigns
  "⠨⠙": "ound",
  "⠨⠑": "ance",
  "⠨⠝": "sion",
  "⠨⠎": "less",
  "⠨⠞": "ount",
  "⠰⠑": "ence",
  "⠰⠛": "ong",
  "⠰⠇": "full",
  "⠰⠝": "tion",
  "⠰⠎": "ness",
  "⠰⠞": "ment",
  "⠰⠽": "ity",
};
