name: Build and Deploy
on: 
  push:
  workflow_dispatch:
env: 
  JWKS_URL: ${{ vars.VITE_AUTHORITY }}/.well-known/jwks.json
  AUTH_AUDIENCE: ${{ vars.VITE_CLIENT_ID }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  VITE_CLIENT_ID: ${{ vars.VITE_CLIENT_ID }}
  VITE_AUTHORITY: ${{ vars.VITE_AUTHORITY }}
  VITE_HOST: ${{ vars.VITE_HOST }}
  VITE_AUTOGRADING: ${{ vars.VITE_AUTOGRADING }}
jobs:
  deploy:
    runs-on: prod-server
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: build and deploy
        run: |
          docker-compose build
          docker-compose up -d
